//
// CouponAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



public class CouponAPI {
    /**
     check coupon
     
     - parameter id: (path) The order ID. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func couponIdGet(id: String, completion: @escaping ((_ data: CouponResponse?,_ error: Error?) -> Void)) {
        couponIdGetWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     check coupon
     - GET /coupon/{id}
     - examples: [{contentType=application/json, example={
  "valid" : true,
  "discount" : 0.8008282
}}]
     
     - parameter id: (path) The order ID. 

     - returns: RequestBuilder<CouponResponse> 
     */
    public class func couponIdGetWithRequestBuilder(id: String) -> RequestBuilder<CouponResponse> {
        var path = "/coupon/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CouponResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
