//
// PaymentAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



public class PaymentAPI {
    /**
     get route by ticket number
     
     - parameter body: (body) Payment data 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func payPut(body: PaymentRequest, completion: @escaping ((_ data: PaymentResponse?,_ error: Error?) -> Void)) {
        payPutWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     get route by ticket number
     - PUT /pay
     - examples: [{contentType=application/json, example={
  "status" : "status"
}}]
     
     - parameter body: (body) Payment data 

     - returns: RequestBuilder<PaymentResponse> 
     */
    public class func payPutWithRequestBuilder(body: PaymentRequest) -> RequestBuilder<PaymentResponse> {
        let path = "/pay"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<PaymentResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
