# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodOnRails' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SwiftyUserDefaults'
  pod 'OHHTTPStubs/Swift'
  pod 'RealmSwift'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'

  # Pods for FoodOnRails

  target 'FoodOnRailsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodOnRailsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
