//
// CafeDishResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class CafeDishResponse: Codable {

    public var id: String
    public var name: String
    public var description: String?
    public var price: Int
    public var imageUrl: String


    
    public init(id: String, name: String, description: String?, price: Int, imageUrl: String) {
        self.id = id
        self.name = name
        self.description = description
        self.price = price
        self.imageUrl = imageUrl
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(id, forKey: "id")
        try container.encode(name, forKey: "name")
        try container.encodeIfPresent(description, forKey: "description")
        try container.encode(price, forKey: "price")
        try container.encode(imageUrl, forKey: "image_url")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decode(String.self, forKey: "id")
        name = try container.decode(String.self, forKey: "name")
        description = try container.decodeIfPresent(String.self, forKey: "description")
        price = try container.decode(Int.self, forKey: "price")
        imageUrl = try container.decode(String.self, forKey: "image_url")
    }
}

