//
// CouponResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class CouponResponse: Codable {

    public var valid: Bool
    public var discount: Float?


    
    public init(valid: Bool, discount: Float?) {
        self.valid = valid
        self.discount = discount
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(valid, forKey: "valid")
        try container.encodeIfPresent(discount, forKey: "discount")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        valid = try container.decode(Bool.self, forKey: "valid")
        discount = try container.decodeIfPresent(Float.self, forKey: "discount")
    }
}

