//
// OrderItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class OrderItem: Codable {

    public var id: String
    public var amount: Int
    public var totalPrice: Int?


    
    public init(id: String, amount: Int, totalPrice: Int?) {
        self.id = id
        self.amount = amount
        self.totalPrice = totalPrice
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(id, forKey: "id")
        try container.encode(amount, forKey: "amount")
        try container.encodeIfPresent(totalPrice, forKey: "total_price")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decode(String.self, forKey: "id")
        amount = try container.decode(Int.self, forKey: "amount")
        totalPrice = try container.decodeIfPresent(Int.self, forKey: "total_price")
    }
}

