//
// OrderCreateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class OrderCreateResponse: Codable {

    public var id: String
    public var paymentUrl: String
    public var status: String
    public var coupon: String?
    public var positions: [OrderItem]


    
    public init(id: String, paymentUrl: String, status: String, coupon: String?, positions: [OrderItem]) {
        self.id = id
        self.paymentUrl = paymentUrl
        self.status = status
        self.coupon = coupon
        self.positions = positions
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(id, forKey: "id")
        try container.encode(paymentUrl, forKey: "payment_url")
        try container.encode(status, forKey: "status")
        try container.encodeIfPresent(coupon, forKey: "coupon")
        try container.encode(positions, forKey: "positions")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decode(String.self, forKey: "id")
        paymentUrl = try container.decode(String.self, forKey: "payment_url")
        status = try container.decode(String.self, forKey: "status")
        coupon = try container.decodeIfPresent(String.self, forKey: "coupon")
        positions = try container.decode([OrderItem].self, forKey: "positions")
    }
}

