//
// OrderRequestOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class OrderRequestOrder: Codable {

    public var cafeId: String
    public var coupon: String?
    public var positions: [OrderItem]


    
    public init(cafeId: String, coupon: String?, positions: [OrderItem]) {
        self.cafeId = cafeId
        self.coupon = coupon
        self.positions = positions
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(cafeId, forKey: "cafe_id")
        try container.encodeIfPresent(coupon, forKey: "coupon")
        try container.encode(positions, forKey: "positions")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        cafeId = try container.decode(String.self, forKey: "cafe_id")
        coupon = try container.decodeIfPresent(String.self, forKey: "coupon")
        positions = try container.decode([OrderItem].self, forKey: "positions")
    }
}

