//
// OrderRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class OrderRequest: Codable {

    public var userId: String
    public var order: OrderRequestOrder


    
    public init(userId: String, order: OrderRequestOrder) {
        self.userId = userId
        self.order = order
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(userId, forKey: "user_id")
        try container.encode(order, forKey: "order")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        userId = try container.decode(String.self, forKey: "user_id")
        order = try container.decode(OrderRequestOrder.self, forKey: "order")
    }
}

