//
// PaymentRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class PaymentRequest: Codable {

    public var userId: String
    public var paymentId: String


    
    public init(userId: String, paymentId: String) {
        self.userId = userId
        self.paymentId = paymentId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(userId, forKey: "user_id")
        try container.encode(paymentId, forKey: "payment_id")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        userId = try container.decode(String.self, forKey: "user_id")
        paymentId = try container.decode(String.self, forKey: "payment_id")
    }
}

