//
// RouteResponseStops.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class RouteResponseStops: Codable {

    public var cityId: String
    public var name: String
    public var dateTime: Date
    public var duration: Int
    public var cafes: [CafeResponse]


    
    public init(cityId: String, name: String, dateTime: Date, duration: Int, cafes: [CafeResponse]) {
        self.cityId = cityId
        self.name = name
        self.dateTime = dateTime
        self.duration = duration
        self.cafes = cafes
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(cityId, forKey: "city_id")
        try container.encode(name, forKey: "name")
        try container.encode(dateTime, forKey: "date_time")
        try container.encode(duration, forKey: "duration")
        try container.encode(cafes, forKey: "cafes")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        cityId = try container.decode(String.self, forKey: "city_id")
        name = try container.decode(String.self, forKey: "name")
        dateTime = try container.decode(Date.self, forKey: "date_time")
        duration = try container.decode(Int.self, forKey: "duration")
        cafes = try container.decode([CafeResponse].self, forKey: "cafes")
    }
}

